### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by bluecamel** [Miker2808/Robot-Contorl-Qt-GUI-With-ROS#1] opened 2022-09-25 17:38 UTC
Hi, there.  Thanks so much for sharing this project.  I'm excited to use it, but have had issues getting it to build.

In QtCreator GUI, I can't get very far at all.  I run it from a ros-sourced bash session, but it can't even find `ament_cmake`, so I must be missing something.  I know that it's there, because I can run cmake manually in the directory and it finds all dependencies.  However, neither make nor `colcon build` work either, and give the following error output:

```
$ make
[ 12%] Automatic MOC and UIC for target ros2_robot_gui
[ 12%] Built target ros2_robot_gui_autogen
make[2]: *** No rule to make target '/home/bluecamel/B/Robot-Contorl-Qt-GUI-With-ROS/qml/SixWheelBotQGUI.qmlproject.qtds', needed by 'ros2_robot_gui_autogen/EWIEGA46WW/qrc_qml.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/ros2_robot_gui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

```
$ colcon build
Starting >>> ros2_robot_gui
--- stderr: ros2_robot_gui
make[2]: *** No rule to make target '/home/bluecamel/B/Robot-Contorl-Qt-GUI-With-ROS/qml/SixWheelBotQGUI.qmlproject.qtds', needed by 'ros2_robot_gui_autogen/EWIEGA46WW/qrc_qml.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/ros2_robot_gui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< ros2_robot_gui [0.91s, exited with code 2]

Summary: 0 packages finished [1.12s]
  1 package failed: ros2_robot_gui
  1 package had stderr output: ros2_robot_gui
```

Unfortunately, my Qt skills are pretty lacking, so I'm struggling to find a way past this.  Any help or advice would be much appreciated 🙏🏼

**Comment by bluecamel** [comment] 2022-09-26 06:46
With a [couple of changes](https://github.com/bluecamel/Robot-Contorl-Qt-GUI-With-ROS/commit/87da9707083727e24be8c641cf558b38947d1a2f), I got past this and on to a new error:

```
$ cmake --build build2
[ 12%] Automatic MOC and UIC for target ros2_robot_gui
[ 12%] Built target ros2_robot_gui_autogen
Consolidate compiler generated dependencies of target ros2_robot_gui
[ 25%] Building CXX object CMakeFiles/ros2_robot_gui.dir/ros2_robot_gui_autogen/mocs_compilation.cpp.o
In file included from /home/bluecamel/B/Robot-Contorl-Qt-GUI-With-ROS/build2/ros2_robot_gui_autogen/EWIEGA46WW/moc_backend.cpp:9,
                 from /home/bluecamel/B/Robot-Contorl-Qt-GUI-With-ROS/build2/ros2_robot_gui_autogen/mocs_compilation.cpp:2:
/home/bluecamel/B/Robot-Contorl-Qt-GUI-With-ROS/build2/ros2_robot_gui_autogen/EWIEGA46WW/../../../backend.h:62:5: error: ‘QML_ELEMENT’ does not name a type
   62 |     QML_ELEMENT
      |     ^~~~~~~~~~~
make[2]: *** [CMakeFiles/ros2_robot_gui.dir/build.make:268: CMakeFiles/ros2_robot_gui.dir/ros2_robot_gui_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/ros2_robot_gui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Miker2808** [comment] 2022-09-26 07:40
Are you attempting to build ROS2 or ROS1?
the file: `SixWheelBotQGUI.qmlproject.qtds` is from the ROS1 project. but from the folder names it appears you wish to get the ROS2 project.
Please note that the ROS2 changed the qml files to main.qml instead of 'SixWheelBotQGUI.qml'
therefore ros2 build will have no idea about the SixWheelBotQGui and will be unable to find it.
Please check what branch are you using (2 branches available for ROS1, and one for ROS2).
Attempt to build without changing the project - is this issue coming from building right after clone/fork?
Cleaning cache if available might solve issues with paths, running qmake ('cmake' for ROS2 project) from qt creator will generate new configurations based on your computer's path.
note: when building for ROS2, build using colcon build, and not cmake.
another note: cmake will be used to configure the project, but colcon build to build the binaries.
I will take another look today at the project as to see the precise steps for building the project.

in {project}/qml/main.qmlproject please change the text "SixWheelBotQGUI.qml" to "main.qml" in line 6

remove all cache (.user files) and remove all previous builds. 
run cmake again, and build using "colcon build" 
if you wish to make a package uncomment line 104 of CMakeLists.txt
(A package allows to run the gui using "ros2 run <project> <build>" (requires sourcing project setup)  instead of "./build"

Having more information about what version of ros you are trying to make, will help me further.

**Comment by bluecamel** [comment] 2022-09-27 04:21
Yes, I'm trying to build for ROS 2, using the Foxy branch, but I'm running Galactic.  This is what I get when building a fresh clone.  I've done fresh clones a few times and always get the same results.  That is, aside from the changes that I linked (including the one you mentioned).  I've also tried colcon, but I get the same error.  I'll spend some more time on it sometime this week and see if I can find what's wrong.

**Comment by Miker2808** [comment] 2022-09-27 20:50
File qml.qrc at line 188 was the cause of the issue. removing this line solved the problem for me.

After this issue I had Qt5Positioning not working due to find_package failing to find the appropriate cmake.
adding: `list(APPEND CMAKE_PREFIX_PATH "~/Qt/5.15.2/gcc_64/lib/cmake")` solved the issue for me. **Note the Qt version and installation path.**

Additionally, the best method to build the project will be through qtcreator with colcon.

By heading to QtCreator -> Projects (When the project is loaded) -> Build & Run -> build -> _scroll down to_ "build steps".
Add custom process step, in "Command" use "colcon", in "Argument" use "build", for "Working Directory" choose this cloned project directory. Then, disable or remove the previous process (cmake). 

After building with QtCreator, head to the build directory and launch the GUI using a terminal with ros2 setup sourced.

Will push a fix for the issues once I get more free time. try these steps for now. close the issue if the issue is solved.

Tested with ROS2 Galactic, Ubuntu 20 LTS

**Closed as completed** 2022-11-03 15:28 UTC
